"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _post_card from './post-card.bones.json'

registerBones({
  "post-card": _post_card,
})
